### ISSUE TITLE
Deprecated method for iOS 9

### ISSUE THREAD

**Issue by grzegorzkrukowski** [google/gtm-oauth#17]
GTMOAuth/GTMOAuthAuthentication.m:986:18: 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).

GTMOAuthAuthentication.m:998:29: 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding.

GTMOAuthViewControllerTouch.m:249:44: 'applicationFrame' is deprecated: first deprecated in iOS 9.0 - Use -[UIScreen bounds]

GTMOAuthViewControllerTouch.m:616:37: 'shouldAutorotateToInterfaceOrientation:' is deprecated: first deprecated in iOS 6.0

GTMHTTPFetcher.m:381:44: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)

**Comment by thomasvl** [comment]
At this point we probably aren't doing any updates here as most use of Google services should be use the OAuth 2 library instead. If you want to do send it a pull request to fix things up because you need OAuth 1 for something else, we can look at landing it.
