### ISSUE TITLE
Podspec

### ISSUE THREAD

**Issue by kikin81** [google/gtm-oauth#19]
I have a legacy native iOS app that depends on the pod
`'gtm-oauth' '0.0.1'`

The podspect at [cocoapods](https://github.com/CocoaPods/Specs/blob/master/Specs/gtm-oauth/0.0.1/gtm-oauth.podspec.json) is outdated as it points to http://code.google.com/p/gtm-oauth.

Please add a podspec to this project.

**Comment by thomasvl** [comment]
We don't control that pod.  You'll need to reach out to the people that do.  The pods we don't control are checked into the repositories they go with.
